### ISSUE TITLE
Limit rental amounts and durations V2

### ISSUE THREAD

**Issue by longhorns709** [Madpeterz/StreamAdmin#131]
**Is your feature request related to a problem? Please describe.**
Hello I would like to see if  we can have the options to limit the option for the a limit amount and a duration amount for rentals

**Describe the solution you'd like**
Setting a venter to only allow 1 rental per avatar with a max limit of 2 weeks.

**Describe alternatives you've considered**
nope

**Additional context**
nope

**Comment by Madpeterz** [comment]
new global config values:

- limitStreams [true/false]
- limitTime [true/false]
- maxStreamTimeDays [number >= 7, <= 365]
- maxTotalStreams [number >= 1, <= 2000]

new per package config values:
- enforceCustomMaxStreams [true/false]
- maxStreamsInPackage   [number >= 1, <= 2000]

# how the system checks on Buy:

when you buy a stream the  limitStreams  flag is checked, 
- if false no other tests are done (this bypasses per package config) and the customer will be able to buy the stream if not banned. 

- if true then the total streams the customer has is checked, it must be lower than maxTotalStreams or they

will not be able to buy the stream.

next enforceCustomMaxStreams is checked, 
- if true then the total streams they have in that package is checked if its not less than maxStreamsInPackage  they will not be able to buy the new stream.


# how the system checks on Renewal
the system checks if the limitTime flag is set to true.
otherwise it continues the renewal.

if it is set then if checks if the current time left in days is more than maxStreamTimeDays if it is then the
renewal is rejected.

then it checks if adding the days * multipler from the renewal would take them over maxStreamTimeDays 
if so then the renewal is rejected.


fixed by: https://github.com/Madpeterz/StreamAdmin/commit/b97e07c91da76aa1fc4301302eb5a851f898d7db
